### ISSUE TITLE
🐛 biomejs.biome/biome __print_socket, errors occurred while executing I/O operations

### ISSUE THREAD

**Issue by MuhammadSawalhy** [biomejs/biome#1942]
### Environment information

```block
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.0.29"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. Installed biome and biome extension for VSCode in WSL2 (+Win10) and everything was OK
2. I shut down my computer at night and after I woke up  I booted into Win10 to continue working
3. Opened VSCode to see that biome extension has trouble and here is the error message

![image](https://github.com/biomejs/biome/assets/42011920/abb18182-7f19-4ae9-bf72-81d1d6214688)

```
[Error - 9:53:18 AM] Restarting client failed
Error: Command "/home/ms/.vscode-server/data/User/workspaceStorage/38160b8c8cbe8ba86b5a56db885f791a/biomejs.biome/biome __print_socket" exited with code 1
Output:
internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Errors occurred while executing I/O operations.
    
    Caused by:
      Connection refused (os error 111)
  


	at getSocket (/home/ms/.vscode-server/extensions/biomejs.biome-2.1.2/out/main.js:37702:11)
	at runNextTicks (node:internal/process/task_queues:60:5)
	at process.processTimers (node:internal/timers:509:9)
	at async createMessageTransports (/home/ms/.vscode-server/extensions/biomejs.biome-2.1.2/out/main.js:37716:16)
	at async LanguageClient2.createConnection (/home/ms/.vscode-server/extensions/biomejs.biome-2.1.2/out/main.js:15897:28)
	at async LanguageClient2.start (/home/ms/.vscode-server/extensions/biomejs.biome-2.1.2/out/main.js:15470:30)
	at async activate (/home/ms/.vscode-server/extensions/biomejs.biome-2.1.2/out/main.js:37535:3)
	at async c.n (/home/ms/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/workbench/api/node/extensionHostProcess.js:140:6256)
	at async c.m (/home/ms/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/workbench/api/node/extensionHostProcess.js:140:6219)
	at async c.l (/home/ms/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/out/vs/workbench/api/node/extensionHostProcess.js:140:5676)

```

### Expected result

The VSCode extension to work as expected.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by MuhammadSawalhy** [comment]
I reopened VSCode after a while and the problem is gone, don't know why!

**Comment by Conaclos** [comment]
Thanks! Please reopen an issue if you encounter again the issue.

**Comment by OleksandrKucherenko** [comment]
```
[Error - 12:31:37 PM] Biome client: couldn't create connection to server.
Error: Command "/Users/o.kucherenko2/Library/Application Support/Code/User/workspaceStorage/3c238daf8a85c25c062596a4d9067a06/biomejs.biome/biome __print_socket" exited with code 1
Output:
internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Errors occurred while executing I/O operations.
    
    Caused by:
      Permission denied (os error 13)
  


    at getSocket (/Users/o.kucherenko2/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36539:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createMessageTransports (/Users/o.kucherenko2/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36553:16)
    at LanguageClient2.createConnection (/Users/o.kucherenko2/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15548:28)
    at LanguageClient2.start (/Users/o.kucherenko2/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15124:30)
    at activate (/Users/o.kucherenko2/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36294:3)
    at K0.n (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
    at K0.m (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
    at K0.l (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
[cli-stderr] finish
```

I has the same problem right now. 

how to solve it?
