### ISSUE TITLE
☂️ GritQL Formatter

### ISSUE THREAD

**Issue by arendjr** [biomejs/biome#2476]
## Description

This issue will act as the hub for tracking the GritQL formatter as it gets built out. Listed here are all of the different pieces that will need to be implemented to get "complete" support in place.

To see how this issue fits into our plugin efforts, please look at the overview here: https://github.com/biomejs/biome/issues/2463

## How to Contribute

Everyone is welcome to contribute pieces here! Some of these may also be good first issues, so if you're looking for guidance, just reach out to us.

If you'd like to tackle something, please leave a comment below this issue for which item(s) of the checklist below you'd like to pick up. We will create a separate issue and assign it to you to simplify tracking.

> [!NOTE]
> In order to have the issue assigned to you, you must comment on this issue.

Please only pick a single piece or group to work on at a time, and try to have time available to work on the piece when you select it so that we can keep progressing quickly. If you need any help or have any questions about our plugin efforts in Biome, feel free to ask in the `#plugins` channel in Discord.

## Testing

Since GritQL is quite a new language, there is no reference formatter to base our efforts on. However, there is a [Grit stdlib](https://github.com/getgrit/stdlib) that has a wide variety of common patterns that can be used as reference. It's probably best if we start by taking some of their patterns and using them as "expected results" in our test suite. Then we can mangle the formatting and verify the formatter returns them as expected.

## Formatting Infrastructure

Listed here are various things that are ready to be implemented or fixed that apply to the GritQL formatter in general.

- [x] Configuration
    - We need to add GritQL as a language in the configuration format, and let it support the common options around indentation, line length and type of newlines.
- [x] Add test suite
- [x] Introduce a `can_format_grit_yet` flag into `biome_service`
- [x] Comment placement
- [x] Handle `biome ignore: format` suppression comments in appropriate places

## GritQL node types

This is a guide that covers most of the nodes that need formatting rules:

- [x] Patterns
  - [x] `before` / `after`
  - [x] `any` / `some` / `every` / `and` / `or`
  - [x] `bubble`
  - [x] `contains` / `includes` / `within`
  - [x] `if`
  - [x] `like` / `where`
  - [x] assignments
  - [x] rewrites
  - [x] lists and maps
  - [x] math operators
- [x] Predicates
  - [x] `any` / `and` / `or`
  - [x] `if`
  - [x] assignments
  - [x] accumulators
  - [x] match operator
  - [x] rewrites
  - [x] returns
- [x] Function calls (node-likes)
- [x] Code snippets

## Releasability

These tasks need to be completed for the GritQL formatter to be "publicly available" with parity with the JS formatter:

- [x] Support GritQL files in the playground
- [x] Support GritQL configuration options in the playground

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/biomejs) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/biomejs/biome/issues/2476">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/biomejs/biome/issues/2476/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/biomejs/biome/issues/2476/pledge.svg">
</picture>
</a>

**Comment by abidjappie** [comment]
I'd like to help out with GritQL, it looks interesting!

Is there any recommended starting point? otherwise, I'm interested in `Function calls` if I can get some guidance to build it 🙇

**Comment by ematipico** [comment]
Thank you @abidjappie 

The first thing to do is to create the crate `biome_gritql_formatter` and run the code gen. There's a contribution guide that you can reach from the mean contribution.md document.

**Comment by arendjr** [comment]
@abidjappie Thanks! If you prefer, I can also set up the basic infrastructure in a PR first so you can focus on a more specific part of the formatter. Just let me know what you prefer!

**Comment by abidjappie** [comment]
I don't mind having a look at the basic infrastructure sometime this weekend. I don't want to delay the development of this feature, so if it's okay that I can have it ready within a day or two I can take it! 🙇 As the @arendjr mentioned, we want to keep this one progressing quickly!

**Comment by ematipico** [comment]
There's no pressure here!

**Comment by abidjappie** [comment]
I gave it a try, please have a look at https://github.com/biomejs/biome/pull/2837 and let me know if I'm on the right track.

**Comment by arendjr** [comment]
Great start, @abidjappie ! I'll assign this issue to you so it's yours to finish at your own pace. Just keep in mind Polar.sh enforces a 6 month limit on the bounties, but otherwise there's no rush.

**Comment by yossydev** [comment]
hi, is this issue going ahead now? 👀

**Comment by yossydev** [comment]
hi, is this issue going ahead now? 👀

**Comment by arendjr** [comment]
Good question! After the initial infrastructure it went silent. @abidjappie are you still interested in continuing this work?

**Comment by branberry** [comment]
Hi! I'd be interested in contributing to this as well.

**Comment by arendjr** [comment]
@branberry I’d say contributions are welcome regardless! So if you’re happy to chip in, feel free to send PRs!

As for the bounty, it looks like it was opened 5 months ago and if I’m not mistaken Polar.sh has a 6 month expiry, so I think it expires in a month. I think it’s good to check with @morgante to check if he’s willing to renew, so you’d still be eligible even if it takes a bit longer.

That said, it’s currently assigned to @abidjappie so if they want to finish it within the remaining month it’s only fair they remain eligible (this is also in accordance with our governance rules).

**Comment by branberry** [comment]
Thanks for the reply! As for the bounty, I'm not concerned with that at all. I'm looking to poke around a bit a learn more about Biome and its codebase, so I'll be on a very slow timeline haha! 

Is the expectation to have each checkbox in the original post completed by a single individual for the bounty? I was thinking of possibly grabbing one or two as a way to dip my toes in the codebase a bit.

**Comment by ematipico** [comment]
I'd say to unassign @abidjappie, and assign the issue to @branberry.

It's been months without tangible progresses, so let's go ahead, and see if @morgante wants to renew the bounty

**Comment by ematipico** [comment]
> Is the expectation to have each checkbox in the original post completed by a single individual for the bounty? I was thinking of possibly grabbing one or two as a way to dip my toes in the codebase a bit.

No, a bounty can be split among multiple contributors

**Comment by morgante** [comment]
I probably won't renew the bounty, mostly because it didn't seem to incentivize much progress and it's no longer a high priority for me.

I'd still love to see this implemented.

**Comment by abidjappie** [comment]
Sorry for the slow response, I've been incredibly busy recently. 

I'm happy to have it handed over to @branberry, and hopefully when I have capacity I can help out again. I recently introduced GritQL to my team's project so I feel a bit more familiar with it's syntax!

**Comment by Arian8j2** [comment]
Hello, I don't know if this is the right place to report this but i write this here, if it needs it's own issue to be opened please let me know. `biome_grit_parser::parse_grit` panics when parsing
```grit
engine marzano(0.1)
language python

`
if $cond:
    $if_body
else:
    $else_body
` as $cond_body where {
    $if_body <: block(statements = [`$var = $if_value`]),
    $else_body <: block(statements = [`$var = $else_value`]),
    $cond_body => `$var = $if_value if $cond else $else_value`,
}
```
with this back trace:
```
thread 'main' panicked at biome-d49ce8898b420a50/6ea885f/crates/biome_parser/src/diagnostic.rs:350:14:
Expected token to be a punctuation or keyword.
stack backtrace:
   4: core::option::Option<T>::expect
             at /.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:933:21
   5: biome_parser::diagnostic::expected_token
             at /.cargo/git/checkouts/biome-d49ce8898b420a50/6ea885f/crates/biome_parser/src/diagnostic.rs:348:9
   6: biome_parser::Parser::expect
             at /.cargo/git/checkouts/biome-d49ce8898b420a50/6ea885f/crates/biome_parser/src/lib.rs:422:24
   7: biome_grit_parser::parser::parse_root
             at /.cargo/git/checkouts/biome-d49ce8898b420a50/6ea885f/crates/biome_grit_parser/src/parser/mod.rs:91:5
   8: biome_grit_parser::parse_grit_with_cache::{{closure}}
             at /.cargo/git/checkouts/biome-d49ce8898b420a50/6ea885f/crates/biome_grit_parser/src/lib.rs:26:9
   9: tracing::span::Span::in_scope
             at /.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.41/src/span.rs:1102:9
  10: biome_grit_parser::parse_grit_with_cache
             at /.cargo/git/checkouts/biome-d49ce8898b420a50/6ea885f/crates/biome_grit_parser/src/lib.rs:23:5
  11: biome_grit_parser::parse_grit
             at /.cargo/git/checkouts/biome-d49ce8898b420a50/6ea885f/crates/biome_grit_parser/src/lib.rs:18:5
```
it's not just this pattern that makes it panic, there are lots of other patterns that trigger it too, you can test patterns in [stdlib](https://github.com/getgrit/stdlib)

**Comment by ematipico** [comment]
@Arian8j2 This isn't the right place, please [file a new issue](https://github.com/biomejs/biome/issues/new?assignees=&labels=S-Needs+triage&projects=&template=03_bug.yml&title=%F0%9F%90%9B+%3CTITLE%3E)
