### ISSUE TITLE
🐛 Biome server crash on this utility type in 1.7.2

### ISSUE THREAD

**Issue by sylvainpolletvillard** [biomejs/biome#2702]
### Environment information

```block
CLI:
  Version:                      1.7.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v21.0.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.4.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. Open VSCode with latest Biome extension on a fresh new TypeScript file
2. Type this code
```ts
export type NonFunctionPropNames<T> = {
  [K in keyof T]: T[K] extends (...rest: unknown[]) => unknown ? never : K
}[keyof T]
```

The Biome server crashes continuously and shut down after 5 tries

This is what i got from output tab:
> [Error - 12:59:33 AM] Request textDocument/codeAction failed.
  Message: panicked at crates\biome_js_semantic\src\semantic_model\scope.rs:115:33:
no entry found for key
Backtrace: disabled backtrace
  Code: -32603 
PanicError { info: "panicked at crates\\biome_js_semantic\\src\\semantic_model\\scope.rs:115:33:\nno entry found for key", backtrace: Some(<disabled>) }

I tried to rollback to Biome 1.7.1 and has no crash, so this bug has been introduced in 1.7.2

### Expected result

No crash, this is valid TS code

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by sylvainpolletvillard** [comment]
closed as duplicate of https://github.com/biomejs/biome/issues/2683
