### ISSUE TITLE
🐛 @biomejs/wasm-nodejs doesn't work

### ISSUE THREAD

**Issue by ianzone** [biomejs/biome#2744]
### Environment information

```block
CLI:
  Version:                      1.7.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.12.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/9.0.6"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

Reproduce:
1. clone https://github.com/ianzone/vite-plugin-biomejs/tree/wasm-bug
2. pnpm i
3. pnpm nx test e2e
4. open the dev server link
5. see error

Output
```bash
 󰰶 ❯ nx test e2e

   ✔  1/1 dependent project tasks succeeded [1 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run e2e:test


> e2e@ test /home/ian/vite-plugin-biomejs/packages/e2e
> vite

  VITE v5.2.11  ready in 355 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
panicked at crates/biome_service/src/settings.rs:57:14:
You must have at least one workspace.

Stack:

Error
    at module.exports.__wbg_new_abda76e883ba8a5f (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/wasm-nodejs/biome_wasm.js:812:17)
    at wasm://wasm/024e26b2:wasm-function[8597]:0x78f84d
    at wasm://wasm/024e26b2:wasm-function[4766]:0x6a919a
    at wasm://wasm/024e26b2:wasm-function[6845]:0x761bca
    at wasm://wasm/024e26b2:wasm-function[6693]:0x711d89
    at wasm://wasm/024e26b2:wasm-function[7181]:0x77ad9a
    at wasm://wasm/024e26b2:wasm-function[457]:0x28fd4c
    at wasm://wasm/024e26b2:wasm-function[128]:0x136497
    at wasm://wasm/024e26b2:wasm-function[5688]:0x6eacd7
    at Workspace.pullDiagnostics (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/wasm-nodejs/biome_wasm.js:549:18)


panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot_core-0.9.9/src/thread_parker/wasm.rs:26:9:
Parking not supported on this platform

Stack:

Error
    at module.exports.__wbg_new_abda76e883ba8a5f (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/wasm-nodejs/biome_wasm.js:812:17)
    at wasm://wasm/024e26b2:wasm-function[8597]:0x78f84d
    at wasm://wasm/024e26b2:wasm-function[4766]:0x6a919a
    at wasm://wasm/024e26b2:wasm-function[7131]:0x770233
    at wasm://wasm/024e26b2:wasm-function[8585]:0x78f3cb
    at wasm://wasm/024e26b2:wasm-function[1811]:0x4d184b
    at wasm://wasm/024e26b2:wasm-function[2928]:0x5d2283
    at wasm://wasm/024e26b2:wasm-function[3362]:0x616226
    at Workspace.closeFile (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/wasm-nodejs/biome_wasm.js:532:18)
    at /home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+js-api@0.5.0_@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/js-api/dist/index.js:71:32


7:56:26 PM [vite] Pre-transform error:
panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/parking_lot_core-0.9.9/src/thread_parker/wasm.rs:26:9:
Parking not supported on this platform

Stack:

Error
    at module.exports.__wbg_new_abda76e883ba8a5f (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/wasm-nodejs/biome_wasm.js:812:17)
    at wasm://wasm/024e26b2:wasm-function[8597]:0x78f84d
    at wasm://wasm/024e26b2:wasm-function[4766]:0x6a919a
    at wasm://wasm/024e26b2:wasm-function[7131]:0x770233
    at wasm://wasm/024e26b2:wasm-function[8585]:0x78f3cb
    at wasm://wasm/024e26b2:wasm-function[1811]:0x4d184b
    at wasm://wasm/024e26b2:wasm-function[1737]:0x4c3616
    at wasm://wasm/024e26b2:wasm-function[2377]:0x5604bb
    at wasm://wasm/024e26b2:wasm-function[3173]:0x601016
    at Workspace.openFile (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/wasm-nodejs/biome_wasm.js:397:18)


7:56:26 PM [vite] Internal server error:
  Plugin: vite-plugin-biomejs
  File: /home/ian/vite-plugin-biomejs/packages/e2e/src/main.js
      at WasmError.fromError (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+js-api@0.5.0_@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/js-api/dist/wasm.js:83:16)
      at wrapError (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+js-api@0.5.0_@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/js-api/dist/wasm.js:92:22)
      at Biome.tryCatchWrapper (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+js-api@0.5.0_@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/js-api/dist/index.js:54:40)
      at Biome.withFile (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+js-api@0.5.0_@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/js-api/dist/index.js:58:21)
      at Biome.formatContent (/home/ian/vite-plugin-biomejs/node_modules/.pnpm/@biomejs+js-api@0.5.0_@biomejs+wasm-nodejs@1.7.3/node_modules/@biomejs/js-api/dist/index.js:84:21)
      at TransformContext.transform (file:///home/ian/vite-plugin-biomejs/packages/vite-plugin-biomejs/dist/index.js:23:33)
      at Object.transform (file:///home/ian/vite-plugin-biomejs/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51139:62)
      at async loadAndTransform (file:///home/ian/vite-plugin-biomejs/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53894:29)
      at async viteTransformMiddleware (file:///home/ian/vite-plugin-biomejs/node_modules/.pnpm/vite@5.2.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:63743:32)
```

### Expected result

no error thrown

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
The next release should fix your bug

**Comment by kotlinski** [comment]
I still get this error, running 1.9.3

**Comment by felixranesberger** [comment]
Same here: 

<img width="1398" alt="Image" src="https://github.com/user-attachments/assets/030bb4e8-caa7-401c-bb9b-c756436b91d1" />

**Comment by nhedger** [comment]
@samhh @felixranesberger would you mind opening new issues with the relevant details?
