### ISSUE TITLE
🐛 Biome client: couldn't create connection to server.

### ISSUE THREAD

**Issue by taii03** [biomejs/biome#3294]
### Environment information

```block
CLI:
  Version:                      1.8.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

```
[Error - 2:47:18 AM] Biome client: couldn't create connection to server.
Error: Command "c:\Users\tai\AppData\Roaming\Code\User\workspaceStorage\7b18ebd8664e48898e216bf08265f890\biomejs.biome\biome.exe __print_socket" exited with code 1
Output:
internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Errors occurred while executing I/O operations.
    
    Caused by:
      Access denied. (os error 5)
  
	at getSocket (c:\Users\tai\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:36539:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async createMessageTransports (c:\Users\tai\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:36553:16)
	at async LanguageClient2.createConnection (c:\Users\tai\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:15548:28)
	at async LanguageClient2.start (c:\Users\tai\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:15124:30)
	at async activate (c:\Users\tai\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:36294:3)
	at async c.n (c:\Users\tai\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6256)
	at async c.m (c:\Users\tai\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6219)
	at async c.l (c:\Users\tai\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:5676)
```

I have been using biome quietly for a long time but suddenly it has been sending me this error. One possibility of the problem could be because I was installing LSPs for nvim and some other things as well as the Zed code editor, maybe I touched something I shouldn't have.

This error occurs when opening a file in Visual Studio Code.

![image](https://github.com/biomejs/biome/assets/68031973/66083506-66d4-4fe8-818b-1ec8b717e6d5)

### Expected result

It should not throw an error.

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
Can you provide the [daemon logs](https://biomejs.dev/guides/integrate-in-editor/#daemon-logs) when this issue happens? (You can use `biome clean` to clear existing unrelated logs)

Also it may be helpful if you can provide the file if this issue only happens when openning that one.

**Comment by taii03** [comment]
New day, I turn on the PC to show the daemon logs and **the error no longer appears**, it seems that it was something that was solved with a restart. I don't know why it could have caused it.

This error appeared every time I entered a file, not a specific one.

**Comment by Sec-ant** [comment]
👌 Feel free to reopen with the logs if you encounter the issue again.

**Comment by boar-is** [comment]
For me, installing Redist helped.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by anime-shed** [comment]
I tried to install
```
https://aka.ms/vs/17/release/vc_redist.x64.exe
```
but it is already installed for me. @joaovlsousa did you install any other version too?

Facing this error:
```
Biome binary found at c:\Users\Animesh\.bun\bin\biome.exe
Executing Biome from: c:\Users\Animesh\.bun\bin\biome.exe
[cli-stderr] end
[cli-stdout] end
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli-stderr] close
[cli] exit 0
[cli] close 0
[Error - 6:35:25 PM] Biome client: couldn't create connection to server.
Error: Command "c:\Users\Animesh\.bun\bin\biome.exe __print_socket" exited with code 0
	at n$ (c:\Users\Animesh\.vscode-oss\extensions\biomejs.biome-2.3.2-universal\out\main.js:84:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async i$ (c:\Users\Animesh\.vscode-oss\extensions\biomejs.biome-2.3.2-universal\out\main.js:84:250)
	at async UQ.createConnection (c:\Users\Animesh\.vscode-oss\extensions\biomejs.biome-2.3.2-universal\out\main.js:39:12709)
	at async UQ.start (c:\Users\Animesh\.vscode-oss\extensions\biomejs.biome-2.3.2-universal\out\main.js:39:2940)
	at async $X (c:\Users\Animesh\.vscode-oss\extensions\biomejs.biome-2.3.2-universal\out\main.js:82:28898)
	at async a0._activate (file:///c:/Users/Animesh/AppData/Local/Programs/VSCodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:5653)
	at async a0._waitForDepsThenActivate (file:///c:/Users/Animesh/AppData/Local/Programs/VSCodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:5595)
	at async a0._initialize (file:///c:/Users/Animesh/AppData/Local/Programs/VSCodium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:4958)
```

**Comment by boar-is** [comment]
@anime-shed, did you restart the terminal?

**Comment by anime-shed** [comment]
@boar-is I have restarted the terminal and my system many times after that.
