### ISSUE TITLE
🐛 Can't use VSCode extension (permission denied)

### ISSUE THREAD

**Issue by AndreiTS** [biomejs/biome#334]
### Environment information

```block
Biome rage is too big to share.
Using biome 1.2.2
```

### What happened?

Configuration file required, looking for one.
Config file found at /home/andrei/Documents/GitHub/MercurioWebFrontend/biome.json, enabling Biome extension
Using Biome from /home/andrei/Documents/GitHub/MercurioWebFrontend/node_modules/.bin/biome
[cli-stderr] data 105
[cli-stderr] end
[cli-stderr] finish
[cli-stdout] end
[cli-stdout] finish
[cli] exit 126
[Error - 5:00:04 PM] Biome client: couldn't create connection to server.
Error: Command "/home/andrei/Documents/GitHub/MercurioWebFrontend/node_modules/.bin/biome __print_socket" exited with code 126
Output:
/bin/sh: 1: /home/andrei/Documents/GitHub/MercurioWebFrontend/node_modules/.bin/biome: Permission denied

	at getSocket (/home/andrei/.vscode/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:19600:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async createMessageTransports (/home/andrei/.vscode/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:19615:16)
	at async LanguageClient2.createConnection (/home/andrei/.vscode/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:15576:28)
	at async LanguageClient2.start (/home/andrei/.vscode/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:15152:30)
	at async activate (/home/andrei/.vscode/extensions/biomejs.biome-1.4.2-linux-x64/out/main.js:19421:3)
	at async E.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:6206)
	at async E.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:6169)
	at async E.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:5626)
[cli-stdout] close
[cli] close 126
[cli-stderr] close

### Expected result

-

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by AndreiTS** [comment]
I deleted my node-modules folder and reinstalled the vscode extensions, and it worked
