### ISSUE TITLE
🐛 @biomejs/js-api not compatible with @biomejs/wasm-nodejs 1.9.0

### ISSUE THREAD

**Issue by ericrafalovsky** [biomejs/biome#3881]
### Environment information

```block
CLI:
  Version:                      1.9.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.7.3"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/9.7.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              true
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

The latest versions of `biomejs/js-api` (0.6.2) and `@biomejs/wasm-nodejs` (1.9.0) appear to be incompatible. 

When trying an example similar to that in the [README](https://www.npmjs.com/package/@biomejs/js-api?activeTab=readme)

```
import { Biome, Distribution } from "@biomejs/js-api";

Biome.create({
	distribution: Distribution.NODE, 
}).then(biome => {
    const formatted = biome.formatContent("function f   (a, b) { return a == b; }", {
        filePath: "example.js",
    });
})
```
it crashes with an error of the form: `Error: missing field `kind`. This does not happen with @biomejs/wasm-nodejs` 1.8.3. and appears to be a compatibility issue. 

I see that `biomejs/js-api` "is currently in alpha" and perhaps it's expected for it to not be compatible with the latest releases of `@biomejs/wasm-nodejs` / `@biomejs/biome`? 

### Expected result

It should not throw an error

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by sleewoo** [comment]
though `biomejs/js-api` currently in alpha, it worked pretty well last couple months.
sadly broken with `1.9.0` release

**Comment by pnodet** [comment]
Running into this issue as well.

Can it be improved by having a CI release the `biomejs/js-api` package when other pkg are released?

**Comment by dyc3** [comment]
I think the main problem is that we don't have any integration tests for it. PRs welcome.

**Comment by axetroy** [comment]
Is there any temporary solution for this before a new version is released with a fix?

**Comment by dyc3** [comment]
Sorry, I don't think so. You are welcome to help improve the situation though.

**Comment by sleewoo** [comment]
@ematipico thanks for fix.
but still getting same error

@ericrafalovsky did you test with latest release `1.9.3`?

```
WasmError
    at Function.fromError (node_modules/.pnpm/@biomejs+js-api@0.6.2_@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/js-api/src/wasm.ts:75:10)
    at wrapError (node_modules/.pnpm/@biomejs+js-api@0.6.2_@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/js-api/src/wasm.ts:85:19)
    at Biome.tryCatchWrapper (node_modules/.pnpm/@biomejs+js-api@0.6.2_@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/js-api/src/index.ts:149:19)
    at Biome.withFile (node_modules/.pnpm/@biomejs+js-api@0.6.2_@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/js-api/src/index.ts:158:15)
    at Biome.formatContent (node_modules/.pnpm/@biomejs+js-api@0.6.2_@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/js-api/src/index.ts:195:15)
    at formatSourceCode (packages/dev-utils/src/format.ts:16:13)
    at renderWithFormat (packages/dev-utils/src/render.ts:23:10)
    at worker (packages/dev-utils/src/file-generator.ts:48:21)
    at generateFile (packages/dev-utils/src/file-generator.ts:73:13)
    at typesGenerator (packages/pgxt-cli/src/plugins/types/index.ts:30:15) {
  stackTrace: Error: Error: missing field `kind`
      at module.exports.__wbg_new_796382978dfd4fb0 (node_modules/.pnpm/@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/wasm-nodejs/biome_wasm.js:907:17)
      at wasm://wasm/035fb09e:wasm-function[12718]:0xb0dabf
      at wasm://wasm/035fb09e:wasm-function[7538]:0x9f2591
      at wasm://wasm/035fb09e:wasm-function[3113]:0x76da64
      at Workspace.openFile (node_modules/.pnpm/@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/wasm-nodejs/biome_wasm.js:382:18)
      at <anonymous> (node_modules/.pnpm/@biomejs+js-api@0.6.2_@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/js-api/src/index.ts:163:19)
      at Biome.tryCatchWrapper (node_modules/.pnpm/@biomejs+js-api@0.6.2_@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/js-api/src/index.ts:147:11)
      at Biome.withFile (node_modules/.pnpm/@biomejs+js-api@0.6.2_@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/js-api/src/index.ts:158:15)
      at Biome.formatContent (node_modules/.pnpm/@biomejs+js-api@0.6.2_@biomejs+wasm-nodejs@1.9.3/node_modules/@biomejs/js-api/src/index.ts:195:15)
      at formatSourceCode (packages/dev-utils/src/format.ts:16:13)
```

**Comment by ematipico** [comment]
This hasn't bee released yet

**Comment by sleewoo** [comment]
this is fixed now,
thanks
