### ISSUE TITLE
🐛 Biome client: couldn't create connection to server.

### ISSUE THREAD

**Issue by kraken-afk** [biomejs/biome#429]
### Environment information

```block
CLI:
  Version:                      1.2.2  
  Color support:                true   

Platform:
  CPU Architecture:             x86_64 
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset  
  NO_COLOR:                     unset  
  TERM:                         unset  
  JS_RUNTIME_VERSION:           "v18.12.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.6.12"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

## Biome Vs Code extension just breaking and wouldn't start the lsp server.
So the issue is only in the vscode extension, on Windows 10 platform. It said ```Couldn't create connection```. But the npm package works as expected though

```cmd
Configuration file required, looking for one.
Config file found at c:\Users\<username>\Documents\Dev\<dir>\biome.json, enabling Biome extension
Using Biome from c:\Users\<username>\Documents\Dev\<dir>\node_modules\.bin\biome
[cli-stderr] data 105
[cli-stderr] end
[cli-stdout] end
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli-stderr] close
[cli] exit 1
[cli] close 1
[Error - 8:13:26 AM] Biome client: couldn't create connection to server.
Error: Command "c:\Users\<username>\Documents\Dev\<dir>\node_modules\.bin\biome __print_socket" exited with code 1
Output:
'c:\Users\<username>' is not recognized as an internal or external command,
operable program or batch file.

	at getSocket (c:\Users\<username>\.vscode\extensions\biomejs.biome-1.4.2-win32-x64\out\main.js:19600:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async createMessageTransports (c:\Users\<username>.vscode\extensions\biomejs.biome-1.4.2-win32-x64\out\main.js:19615:16)
	at async LanguageClient2.createConnection (c:\Users\<username>\.vscode\extensions\biomejs.biome-1.4.2-win32-x64\out\main.js:15576:28)
	at async LanguageClient2.start (c:\Users\<username>\.vscode\extensions\biomejs.biome-1.4.2-win32-x64\out\main.js:15152:30)
	at async activate (c:\Users\<username>.vscode\extensions\biomejs.biome-1.4.2-win32-x64\out\main.js:19421:3)
	at async E.n (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:6206)
	at async E.m (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:6169)
	at async E.l (c:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:5626)
```

### Expected result

Start linting Js/Ts file

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by camallen** [comment]
I came across something similar and fixed it by explicitly setting the biome client path in the extension config via `biome.lspBin` as outlined in https://marketplace.visualstudio.com/items?itemName=biomejs.biome#biome-resolution

This is the config that worked for me but your local node path may vary so adjust it accordingly
```
"biome.lspBin": "node_modules/@biomejs/cli-darwin-arm64/biome",
```

**Comment by kraken-afk** [comment]
Seems it doesn't give expected results. I'm guessing it's an OS compatibility issue.
```powershell
Error: Command "c:\Users\Jhon doe\Documents\Dev\dir\node_modules\@biomejs\cli-win32-x64\biome.exe __print_socket" exited with code 1
Output:
'c:\Users\Jhon' is not recognized as an internal or external command,
```
p.s my win username is separated with space

**Comment by ematipico** [comment]
It's definitely a possibility! The output of the command is definitely weird and I wonder why that happens. We should investigate

**Comment by kraken-afk** [comment]
> It's definitely a possibility! The output of the command is definitely weird and I wonder why that happens. We should investigate

Hi, I just create a PR for this issue, it's absurdly simple problem. please review it, thanks 😉😁

**Comment by austinm911** [comment]
I'm getting this error

```
Biome binary found at /Users/am/Coding/v/node_modules/.pnpm/@biomejs+cli-darwin-arm64@1.5.1/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/am/Library/Application%20Support/Cursor/User/workspaceStorage/50933622a7b39cb4c04b4170b8da80c3/biomejs.biome/biome
Executing Biome from: /Users/am/Library/Application Support/Cursor/User/workspaceStorage/50933622a7b39cb4c04b4170b8da80c3/biomejs.biome/biome
[cli-stderr] data 217
[cli] exit 1
[Error - 12:38:09 PM] Biome client: couldn't create connection to server.
Error: Command "/Users/am/Library/Application Support/Cursor/User/workspaceStorage/50933622a7b39cb4c04b4170b8da80c3/biomejs.biome/biome __print_socket" exited with code 1
Output:
internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Errors occurred while executing I/O operations.
    
    Caused by:
      Connection refused (os error 61)
  


    at getSocket (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:37483:11)
    at createMessageTransports (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:37497:16)
    at LanguageClient2.createConnection (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:15897:28)
    at LanguageClient2.start (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:15470:30)
    at activate (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:37316:3)
    at u.n (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:6342)
    at u.m (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:6305)
    at u.l (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:5762)
[Error - 12:38:47 PM] Restarting client failed
Error: Command "/Users/am/Library/Application Support/Cursor/User/workspaceStorage/50933622a7b39cb4c04b4170b8da80c3/biomejs.biome/biome __print_socket" exited with code 1
Output:
internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Errors occurred while executing I/O operations.
    
    Caused by:
      Connection refused (os error 61)
  


    at getSocket (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:37483:11)
    at createMessageTransports (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:37497:16)
    at LanguageClient2.createConnection (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:15897:28)
    at LanguageClient2.start (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:15470:30)
    at activate (/Users/am/.cursor/extensions/biomejs.biome-2.1.1/out/main.js:37316:3)
    at u.n (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:6342)
    at u.m (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:6305)
    at u.l (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:5762)
[cli-stderr] end
[cli-stdout] end
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 1
[cli-stderr] close
```
