### ISSUE TITLE
Vs Code extension not launching on macos

### ISSUE THREAD

**Issue by crusaderincode** [biomejs/biome#4335]
### Environment information

```block
Installed via npm locally on project
```

### What happened?

After launching vs code, extension throw an error: 

`
Biome binary found at /Users/crusader/data/projects/dayhub/dayhub-interface/node_modules/@biomejs/cli-darwin-arm64/biome
Copying binary to temporary folder: file:///Users/crusader/Library/Application%20Support/Code/User/workspaceStorage/cef63b6f70a39189be82687e55bf0d5a/biomejs.biome/biome
Executing Biome from: /Users/crusader/Library/Application Support/Code/User/workspaceStorage/cef63b6f70a39189be82687e55bf0d5a/biomejs.biome/biome
[cli-stderr] data 522
[cli-stderr] data 22
[cli-stderr] data 191
[cli-stderr] data 40
[cli-stderr] end
[cli-stdout] end
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli-stderr] close
[cli] exit 1
[cli] close 1
[Error - 22:48:57] Biome client: couldn't create connection to server.
Error: Command "/Users/crusader/Library/Application Support/Code/User/workspaceStorage/cef63b6f70a39189be82687e55bf0d5a/biomejs.biome/biome __print_socket" exited with code 1
Output:
Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates/biome_cli/src/commands/daemon.rs:216:10
Thread Name: main
Message: Failed to start the logger for the daemon.: InitError { context: "failed to create log directory", source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }

internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Errors occurred while executing I/O operations.
    
    Caused by:
      the server process exited before the connection could be established
  

    at getSocket (/Users/crusader/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36539:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createMessageTransports (/Users/crusader/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36553:16)
    at LanguageClient2.createConnection (/Users/crusader/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15548:28)
    at LanguageClient2.start (/Users/crusader/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:15124:30)
    at activate (/Users/crusader/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:36294:3)
    at m.n (/Users/crusader/data/soft/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:6409)
    at m (/Users/crusader/data/soft/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:6372)
    at m.l (/Users/crusader/data/soft/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:5829)

`

### Expected result

Extension launched 

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
When the Biome server starts, it automatically creates a folder for storing its logs. By default that's where the folder is: https://biomejs.dev/guides/editors/create-a-extension/#daemon-logs

It seems it isn't possible. You could try to set the environment variable differently: https://biomejs.dev/reference/environment-variables/#biome_log_path

**Comment by crusaderincode** [comment]
Thanks for the info. The issue was resolved by setting correct permissions for `/Users/<UserName>/Library/Caches/dev.biomejs.biome`
