### ISSUE TITLE
🐛 Latest version (1.9.4) keeps crashing

### ISSUE THREAD

**Issue by dioggosoares** [biomejs/biome#4615]
### Environment information

```block
VS Code version
1.95.3

Extension version
2.3.0

Biome version
1.9.4

Operating system
 Linux
```

### What happened?

Description
The extension stops to work after some minutes.
![image](https://github.com/user-attachments/assets/6b073ab8-e6d4-46c8-885e-dc9b121e47eb)

Steps to reproduce
I've upgraded and also tried to reinstall the extension

### Expected result

Expected behavior
Don't crash, with the 1.9.3 doesn't crash.

Does this issue occur when using the CLI directly?
Not sure / Not applicable

Logs
```
Connecting to "/home/diogo/.cache/biome/biome-socket-1.9.4" ...
[cli-stderr] data 393
[Error - 12:02:53] Sending document notification textDocument/didOpen failed
Error: This socket has been ended by the other party
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at Socket.writeAfterFIN [as write] (node:net:562:14)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:3008:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:2999:16)
    at StreamMessageWriter.doWrite (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1429:31)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1420:25
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[Error - 12:02:53] Sending document notification textDocument/didOpen failed
Error: This socket has been ended by the other party
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at Socket.writeAfterFIN [as write] (node:net:562:14)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:3008:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:2999:16)
    at StreamMessageWriter.doWrite (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1429:31)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1420:25
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[Info  - 12:02:53] Connection to server got closed. Server will restart.
true
[cli-stderr] end
[cli-stderr] finish
[cli-stdout] end
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
[cli-stdout] data 44
[cli] exit 0
Connecting to "/home/diogo/.cache/biome/biome-socket-1.9.4" ...
[cli-stderr] data 393
[Error - 12:02:54] Sending document notification textDocument/didOpen failed
Error: This socket has been ended by the other party
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at Socket.writeAfterFIN [as write] (node:net:562:14)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:3008:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:2999:16)
    at StreamMessageWriter.doWrite (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1429:31)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1420:25
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[Error - 12:02:54] Sending document notification textDocument/didOpen failed
Error: This socket has been ended by the other party
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at Socket.writeAfterFIN [as write] (node:net:562:14)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:3008:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:2999:16)
    at StreamMessageWriter.doWrite (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1429:31)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1420:25
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[Error - 12:02:54] Sending document notification textDocument/didOpen failed
Error: This socket has been ended by the other party
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at Socket.writeAfterFIN [as write] (node:net:562:14)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:3008:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:2999:16)
    at StreamMessageWriter.doWrite (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1429:31)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1420:25
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[Error - 12:02:54] Client Biome: connection to server is erroring. Shutting down server.
[Error - 12:02:54] Sending document notification textDocument/didOpen failed
Error: This socket has been ended by the other party
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at Socket.writeAfterFIN [as write] (node:net:562:14)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:3008:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:2999:16)
    at StreamMessageWriter.doWrite (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1429:31)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1420:25
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[Error - 12:02:54] Client Biome: connection to server is erroring. Shutting down server.
[Error - 12:02:54] Sending document notification textDocument/didOpen failed
Error: This socket has been ended by the other party
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at Socket.writeAfterFIN [as write] (node:net:562:14)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:3008:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:2999:16)
    at StreamMessageWriter.doWrite (/home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1429:31)
    at /home/diogo/.vscode/extensions/biomejs.biome-2.3.0/out/main.js:1420:25
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
[Error - 12:02:54] Connection to server got closed. Server will not be restarted.
[cli-stderr] end
[cli-stderr] finish
[cli-stdout] end
[cli-stdout] finish
[Error - 12:02:54] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
[Error - 12:02:54] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
[Error - 12:02:54] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
[cli-stdout] close
[cli] close 0
[cli-stderr] close
```

I expect biomejs to automatically format my code following the settings in biome.json

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Please provide: 
- `biome range --daemon-logs`
- a valid reproduction

Also, we suggest starting using the pre release version of the extension, it should fix the problem. Remember to restart VSCode.
