### ISSUE TITLE
🐛 You must have at least one workspace

### ISSUE THREAD

**Issue by johnlindquist** [biomejs/biome#4666]
### VS Code version

Cursor 0.41.3

### Extension version

biome-2024.9.200949

### Biome version

1.9.2

### Operating system

- [ ] Windows
- [ ] macOS
- [ ] Linux

### Description

2024-09-26 16:20:57.099 [info] Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates/biome_service/src/settings.rs:75:14
Thread Name: tokio-runtime-worker
Message: You must have at least one workspace.

2024-09-26 16:20:57.103 [info] [Error - 4:20:57 PM] Handling connection error failed
2024-09-26 16:20:57.103 [info] TypeError: Cannot read properties of undefined (reading 'toString')
	at Object.error (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:48582:28)
	at BiomeLanguageClient.handleConnectionError (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:47045:71)
	at errorHandler (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:46991:19)
	at /Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:47374:37
	at CallbackList.invoke (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:30421:40)
	at Emitter.fire (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:30483:37)
	at writeErrorHandler (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:31532:23)
	at CallbackList.invoke (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:30421:40)
	at Emitter.fire (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:30483:37)
	at StreamMessageWriter.fireError (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:30975:28)
	at Socket.<anonymous> (/Users/johnlindquist/.cursor/extensions/biomejs.biome-2024.9.200949/out/index.js:31012:48)
	at Socket.emit (node:events:514:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-09-26 16:20:57.103 [info] [Error - 4:20:57 PM] Sending document notification textDocument/didOpen failed
2024-09-26 16:20:57.103 [info] Error: write EPIPE
	at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
2024-09-26 16:20:57.104 [info] [Error - 4:20:57 PM] Biome language server error
2024-09-26 16:20:57.104 [info] [Error - 4:20:57 PM] Request textDocument/codeAction failed.
2024-09-26 16:20:57.104 [info]   Message: Cannot call write after a stream was destroyed
  Code: -32099 
2024-09-26 16:20:57.104 [info] [Error - 4:20:57 PM] Connection to server got closed. Server will not be restarted.
2024-09-26 16:20:57.104 [info] [Error - 4:20:57 PM] Stopping server failed
2024-09-26 16:20:57.104 [info]   Message: Cannot call write after a stream was destroyed
  Code: -32099 
2024-09-26 16:20:57.104 [info] [Error - 4:20:57 PM] Stopping server failed
2024-09-26 16:20:57.104 [info]   Message: Cannot call write after a stream was destroyed
  Code: -32099 
2024-09-26 16:24:55.531 [info] Biome encountered an unexpected error

### Steps to reproduce

Simple open your project

### Expected behavior

for it to work

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by ematipico** [comment]
Closing as this has been fixed in `next` and it will be available in v2.

By the way @nhedger, the pre release version still can't use `biome.lsp.bin`. I still need to use the release version to debug :(

**Comment by martinwcf** [comment]
Couldn't fix it with Kurt suggestions but I got it working with:

- Rename biome.json to something else
- Biome: Restart (command in vscode)
- Bring biome.json back
- Biome: Restart

May have had some bad cache that wasn't flushing? I went straight into a git rebase/reflog vortex with lots of conflicts before it happened.
Also formatter.useEditorconfig = true, in case it matters.

**Comment by simiansim** [comment]
For non vscode users... I also experience this constantly with jetbrains webstorm, for a Nodejs api project. I have a populated biome.jsonc config file, and I think it is being validated against: `"./node_modules/@biomejs/biome/configuration_schema.json"`

The plugin in this case is currently **limited to 1.9.0** and so the fix mentioned here is not available. 
https://plugins.jetbrains.com/plugin/22761-biome/versions

**Comment by mauromalara** [comment]
I fixed it by using Node `v24.x` instead of `v20.19`
