### ISSUE TITLE
🐛 Running biome in gitlab ci fails

### ISSUE THREAD

**Issue by bryanjtc** [biomejs/biome#623]
### Environment information

```block
CLI:
  Version:                      1.3.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.12.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/3.6.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. I have a gitlab ci job that runs linters and then pushes the fixed code to the branch.
2. When I add biome this happened
```bash
$ yarn biome lint . --apply-unsafe || export failure=1
node:internal/errors:497
    ErrorCaptureStackTrace(err);
    ^
Error: spawnSync /builds/tech-ayudinga/frontend/design-system/.yarn/unplugged/@biomejs-cli-linux-x64-npm-1.3.1-d0d2c0ccd7/node_modules/@biomejs/cli-linux-x64/biome ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at Object.spawnSync (node:child_process:876:24)
    at Object.<anonymous> (/builds/tech-ayudinga/frontend/design-system/.yarn/unplugged/@biomejs-biome-npm-1.3.1-6f9e52cf26/node_modules/@biomejs/biome/bin/biome:25:42)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at require$$0.Module._extensions..js (/builds/tech-ayudinga/frontend/design-system/.pnp.cjs:35495:33)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at require$$0.Module._load (/builds/tech-ayudinga/frontend/design-system/.pnp.cjs:35340:31)
    at cjsLoader (node:internal/modules/esm/translators:284:17) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /builds/tech-ayudinga/frontend/design-system/.yarn/unplugged/@biomejs-cli-linux-x64-npm-1.3.1-d0d2c0ccd7/node_modules/@biomejs/cli-linux-x64/biome',
  path: '/builds/tech-ayudinga/frontend/design-system/.yarn/unplugged/@biomejs-cli-linux-x64-npm-1.3.1-d0d2c0ccd7/node_modules/@biomejs/cli-linux-x64/biome',
  spawnargs: [ 'lint', '.', '--apply-unsafe' ]
```

### Expected result

It should not throw an error.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
There's a chance that yarn doesn't install optional dependencies in CI environments, can you verify that the package is correctly installed? 

If it doesn't and biome works correctly locally, then that's an issue of the package manager

**Comment by bryanjtc** [comment]
It was a problem with yarn not installing the optional dependencies. Fixed by running biome with npm.
